name: seededntm
channels:
- conda-forge
dependencies:
- _libgcc_mutex=0.1=conda_forge
- _openmp_mutex=4.5=2_gnu
- asttokens=3.0.0=pyhd8ed1ab_1
- aws-c-auth=0.9.1=h48c9088_3
- aws-c-cal=0.9.2=he7b75e1_1
- aws-c-common=0.12.4=hb03c661_0
- aws-c-compression=0.3.1=h92c474e_6
- aws-c-event-stream=0.5.6=h82d11aa_3
- aws-c-http=0.10.4=h94feff3_3
- aws-c-io=0.22.0=h57f3b0d_1
- aws-c-mqtt=0.13.3=h2b1cf8c_6
- aws-c-s3=0.8.6=h4e5ac4b_5
- aws-c-sdkutils=0.2.4=h92c474e_1
- aws-checksums=0.2.7=h92c474e_2
- aws-crt-cpp=0.34.4=h60c762c_0
- aws-sdk-cpp=1.11.606=h32384e2_4
- azure-core-cpp=1.16.1=h3a458e0_0
- azure-identity-cpp=1.13.2=h3a5f585_1
- azure-storage-blobs-cpp=12.15.0=h2a74896_1
- azure-storage-common-cpp=12.11.0=h3d7a050_1
- azure-storage-files-datalake-cpp=12.13.0=hf38f1be_1
- binutils_impl_linux-64=2.44=h9d8b0ac_4
- binutils_linux-64=2.44=h4852527_4
- bzip2=1.0.8=hda65f42_8
- c-ares=1.34.5=hb9d3cd8_0
- ca-certificates=2025.10.5=hbd8a1cb_0
- certifi=2025.10.5=pyhd8ed1ab_0
- cmake=4.1.2=hc85cc9f_0
- decorator=5.2.1=pyhd8ed1ab_0
- exceptiongroup=1.3.0=pyhd8ed1ab_0
- executing=2.2.1=pyhd8ed1ab_0
- gcc_impl_linux-64=15.2.0=hcacfade_7
- gcc_linux-64=15.2.0=h862fb80_12
- gflags=2.2.2=h5888daf_1005
- glog=0.7.1=hbabe93e_0
- gxx_impl_linux-64=15.2.0=h54ccb8d_7
- gxx_linux-64=15.2.0=hfaa183a_12
- hdf5=1.14.6=nompi_h6e4c0c1_103
- ipython=9.6.0=pyhfa0c392_0
- ipython_pygments_lexers=1.1.1=pyhd8ed1ab_0
- jedi=0.19.2=pyhd8ed1ab_1
- kernel-headers_linux-64=3.10.0=he073ed8_18
- keyutils=1.6.3=hb9d3cd8_0
- krb5=1.21.3=h659f571_0
- ld_impl_linux-64=2.44=h1aa0949_4
- lerc=4.0.0=h0aef613_1
- libabseil=20250512.1=cxx17_hba17884_0
- libaec=1.1.4=h3f801dc_0
- libarrow=21.0.0=hf201b43_9_cpu
- libarrow-acero=21.0.0=h635bf11_9_cpu
- libarrow-compute=21.0.0=h8c2c5c3_9_cpu
- libarrow-dataset=21.0.0=h635bf11_9_cpu
- libarrow-substrait=21.0.0=h3f74fd7_9_cpu
- libbrotlicommon=1.1.0=hb03c661_4
- libbrotlidec=1.1.0=hb03c661_4
- libbrotlienc=1.1.0=hb03c661_4
- libcrc32c=1.1.2=h9c3ff4c_0
- libcurl=8.16.0=h4e3cde8_0
- libdeflate=1.24=h86f0d12_0
- libedit=3.1.20250104=pl5321h7949ede_0
- libev=4.33=hd590300_2
- libevent=2.1.12=hf998b51_1
- libexpat=2.7.1=hecca717_0
- libffi=3.5.2=h9ec8514_0
- libgcc=15.2.0=h767d61c_7
- libgcc-devel_linux-64=15.2.0=h73f6952_107
- libgcc-ng=15.2.0=h69a702a_7
- libgfortran=15.2.0=h69a702a_7
- libgfortran5=15.2.0=hcd61629_7
- libgomp=15.2.0=h767d61c_7
- libgoogle-cloud=2.39.0=hdb79228_0
- libgoogle-cloud-storage=2.39.0=hdbdcf42_0
- libgrpc=1.73.1=h3288cfb_1
- libiconv=1.18=h3b78370_2
- libjpeg-turbo=3.1.0=hb9d3cd8_0
- liblzma=5.8.1=hb9d3cd8_2
- libnghttp2=1.67.0=had1ee68_0
- libnsl=2.0.1=hb9d3cd8_1
- libopentelemetry-cpp=1.21.0=hb9b0907_1
- libopentelemetry-cpp-headers=1.21.0=ha770c72_1
- libparquet=21.0.0=h7376487_9_cpu
- libprotobuf=6.31.1=h49aed37_2
- libre2-11=2025.08.12=h7b12aa8_1
- libsanitizer=15.2.0=hb13aed2_7
- libsqlite=3.50.4=h0c1763c_0
- libssh2=1.11.1=hcf80075_0
- libstdcxx=15.2.0=h8f9b012_7
- libstdcxx-devel_linux-64=15.2.0=h73f6952_107
- libstdcxx-ng=15.2.0=h4852527_7
- libthrift=0.22.0=h454ac66_1
- libtiff=4.7.1=h8261f1e_0
- libutf8proc=2.11.0=hb04c3b8_0
- libuuid=2.41.2=he9a06e4_0
- libuv=1.51.0=hb03c661_1
- libwebp-base=1.6.0=hd42ef1d_0
- libxcrypt=4.4.36=hd590300_1
- libxml2=2.15.1=h031cc0b_0
- libxml2-16=2.15.1=hf2a90c1_0
- libzlib=1.3.1=hb9d3cd8_2
- lz4-c=1.10.0=h5888daf_1
- matplotlib-inline=0.2.1=pyhd8ed1ab_0
- ncurses=6.5=h2d0b736_3
- nlohmann_json=3.12.0=h54a6638_1
- openssl=3.5.4=h26f9b46_0
- orc=2.2.1=hd747db4_0
- parso=0.8.5=pyhcf101f3_0
- pexpect=4.9.0=pyhd8ed1ab_1
- pickleshare=0.7.5=pyhd8ed1ab_1004
- pip=25.2=pyh8b19718_0
- proj=9.7.0=hb72c0af_0
- prometheus-cpp=1.3.0=ha5d0236_0
- prompt-toolkit=3.0.52=pyha770c72_0
- ptyprocess=0.7.0=pyhd8ed1ab_1
- pure_eval=0.2.3=pyhd8ed1ab_1
- pyarrow=21.0.0=py311h38be061_1
- pyarrow-core=21.0.0=py311h342b5a4_1_cpu
- pygments=2.19.2=pyhd8ed1ab_0
- pyproj=3.7.2=py311h4e6619b_2
- python=3.11.14=hd63d673_2_cpython
- python_abi=3.11=8_cp311
- re2=2025.08.12=h5301d42_1
- readline=8.2=h8c095d6_2
- rhash=1.4.6=hb9d3cd8_1
- s2n=1.5.26=h5ac9029_0
- setuptools=80.9.0=pyhff2d567_0
- snappy=1.2.2=h03e3b7b_0
- sqlite=3.50.4=hbc0de68_0
- stack_data=0.6.3=pyhd8ed1ab_1
- sysroot_linux-64=2.17=h0157908_18
- tk=8.6.13=noxft_hd72426e_102
- traitlets=5.14.3=pyhd8ed1ab_1
- typing_extensions=4.15.0=pyhcf101f3_0
- tzdata=2025b=h78e105d_0
- wcwidth=0.2.14=pyhd8ed1ab_0
- wheel=0.45.1=pyhd8ed1ab_1
- zlib=1.3.1=hb9d3cd8_2
- zstd=1.5.7=hb8e6e7a_2

